Task 1994
processtech/runawfe-free-server pull request #195
Opened 2020-12-24 18:39 UTC by CrimsonParade

Для фронта были созданы константы в ImportDatafileAction и MessagesOther.
В struts.properties прописаны названия элементов на английском: "Do not change the internal storage path", "Yes", "No".
В struts_ru.properties их русские аналоги, переведенные в UTF:  "Не изменять путь в источнике данных внутреннего хранилища", "Да", "Нет".
В ImportDataFileTag добавлен метод, созданный по аналогии с уже существующим createAddDataRow().

В ImportDataFileAction добавлена булевая переменная, отвечающая за то, будет ли изменяться путь к внутреннему хранилищу.
В DataSourceStorage переработан метод clear(): 
исправлена недоработка, при которой удалялся только путь к внутреннему хранилищу, а не файлы в нём,
в сигнатуру метода добавлена булевая переменная (см. ImportDataFileAction).
В DataSourceStuff добавлены констаты, хранящие расширения Excel-файлов (.xls, .xlsx).

![front](https://user-images.githubusercontent.com/70919069/103103115-73cb2600-4630-11eb-90b3-f9dca8bce6cd.png)

2020-12-26 11:57 UTC, AlexMisha requested changes
В целом ок, есть несколько замечаний

2020-12-26 11:57 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (ds instanceof ExcelDataSource) {
В задаче речь шла только о внутреннем хранилище, т.е. нужна проверка, что это внутреннее хранилище перед очисткой

2020-12-26 11:57 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +                    if (file.isFile() && (file.getName().endsWith(EXCEL_FILE_XLSX_SUFFIX) || file.getName().endsWith(EXCEL_FILE_XLS_SUFFIX))) {
См. реализацию `File.getName()` - это не просто getter

Лучше сохранить в переменную перед сравнением

2020-12-26 11:57 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            DataSource ds = getDataSource(dsName);
Вследствие того, что доработка касается только внутреннего хранилища, то нет необходимости сразу парсить xml, для начала можно просто проверить, что имя ds - internal storage

2020-12-26 11:57 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +                for (File file : Objects.requireNonNull(new File(((ExcelDataSource) ds).getFilePath()).listFiles())) {
Код можно несколько причесать, воспользовавшись классами из `java.nio`

Например, `Files.list`, а дальше через стрим работать

Всякие IOException, думаю, можно просто логировать

2020-12-26 11:57 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (doNotUpdateInternalStorage && dsName.equals(DataSourceStuff.INTERNAL_STORAGE_DATA_SOURCE_NAME)) {
`doNotUpdateInternalStorage` не совсем отражает суть - опция ведь означает, что не будет изменен только путь до внутреннего хранилища

Само внутреннее хранилище - непосредственно excel файлы - будут удалены

Возможно лучше `doNotUpdateInternalStoragePath`? Соответственно по всему PR нужно поправить, если изменим наименование

2020-12-26 12:02 UTC, CrimsonParade commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (ds instanceof ExcelDataSource) {
Если я правильно понял опцию "очистка системы", то Excel-файлы должны удаляться во всех хранилищах, а не только во внутреннем. 
Я что-то неправльно понял по логике или это будет исправлено позже?

2020-12-26 12:16 UTC, CrimsonParade commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (doNotUpdateInternalStorage && dsName.equals(DataSourceStuff.INTERNAL_STORAGE_DATA_SOURCE_NAME)) {
Да, я тоже об этом думал, мне кажется, лучше будет везде поменять `update` на `change`.
`doNotChangeInternalStoragePath` и т.д.

2020-12-26 12:30 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (ds instanceof ExcelDataSource) {
Цитата из постановки:

> При этом сами текущие файлы **внутреннего** хранилища (если выбрана опция удаления данных) надо в хранилище удалить

2020-12-26 12:30 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +            if (doNotUpdateInternalStorage && dsName.equals(DataSourceStuff.INTERNAL_STORAGE_DATA_SOURCE_NAME)) {
Да, согласен

2020-12-26 14:17 UTC, CrimsonParade commented
Доработал все, кроме вынесения `File.getName()` в переменную, ибо можно ли создать переменную внутри `stream.filter()`, нагуглить так и не получилось

2020-12-26 15:04 UTC, CrimsonParade commented
Решил проблему, все замечания доработаны

2020-12-27 11:11 UTC, CrimsonParade commented
> Решил проблему, все замечания доработаны

Проект перестал деплоиться, источником проблемы оказались лямбды, использованные при работе со стримом `(Files.list)`.
Как сообщает интернет, Spring 3 не поддерживает лямбда-выражения.
Избавиться от них и вернуться к обычному `for` или эта проблема решаема?

2020-12-28 08:53 UTC, AlexMisha requested changes
> Хотел использовать лямбды вместо огромных анонимных функций, но со Spring 3, как я понял, они не дружат.

Да, есть такая проблема. Хотя странно, что она проявилась здесь: в wfe-web никакого спринга нет, да и в статике очевидно тоже. Возможно из-за того, что в каких-то компонентах используется `DataSourceStorage`...
Падал странный `IndexOutOfBoundsException`, верно?

Тогда прошу прощения, просьба все-таки вернуть, как было, с обычным java io и циклами, с учетом тех правок, что писал ранее.

2020-12-28 08:53 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/datasource/DataSourceStorage.java
> +                        Files.list(new File(((ExcelDataSource) ds).getFilePath()).toPath())
Вроде бы тут путь можно получить тоже через nio: `Paths.get`

2020-12-28 08:53 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/action/ImportDataFileAction.java
> +            if (CHANGE_INTERNAL_STORAGE_PATH.equals(changeInternalStoragePathParamType) && SystemProperties.getAdministratorName().equals(getLoggedUser(request).getName())) {
Ниже есть строчка - `User user = getLoggedUser(request)`

Можно ее повыше поднять и использовать юзера.
И сразу вычислить, администратор ли он, сохранить в `boolean` переменную

2020-12-28 08:57 UTC, CrimsonParade commented
> Падал странный IndexOutOfBoundsException, верно?

Да, при деплоинге падал `IndexOutOfBoundsException` и Спринг сообщал, что не может загрузить Бин `DataSourceStorage`.

2020-12-28 10:14 UTC, CrimsonParade commented
Вернулся к обычному циклу (с учетом правок), вынес в `isAdmin` информацию о том, является ли пользователь администратором, использовал эту переменную при вычислении `doNotChangeInternalStoragePath`. 
Её же можно использовать при вычислении `clearBeforeUpload`.

2020-12-29 13:37 UTC, AlexMisha approved these changes
Ок, принимается

2020-12-29 13:39 UTC, CrimsonParade commented
PR закрыть?

2020-12-29 14:00 UTC, AlexMisha commented
Да, можно закрыть

2020-12-29 14:01 UTC, closed without merging