Delete button style violation in bot list
processtech/runawfe-free-server pull request #198
Opened 2020-12-29 19:31 UTC by hramovalexey

Corrected alignment of delete button from left to right in bot list table.

2020-12-30 09:45 UTC, AlexMisha reviewed
Ок, но в постановке есть неявное требование:
> Левую же позицию должна занимать кнопка "Добавить" при её наличии

Соответственно просьба "спустить" ссылку "Добавить бота" и сделать ее кнопкой

2020-12-31 06:34 UTC, hramovalexey commented
Да. Этого я не понял. Исправил.

2021-01-05 11:34 UTC, AlexMisha requested changes
В целом ок, но не нравится завязка на конкретное предназначение дополнительной кнопки и количество дополнительных кнопок
Предлагаю рассмотреть возможность реализации с помощью переопределения метода `getSubmitButtonsData`. Пример использования есть в `WFFormTag`
Скорее всего потребуется небольшое расширение для того, чтобы передать `onclick` атрибут

И просьба при разработке использовать [code style](https://runawfe.org/rus/doc/DevelopersInfo#CodeStyle;)

2021-01-06 17:57 UTC, hramovalexey commented
Исправил.
Я в самом начале и хотел сделать через getSubmitButtonsData, но метод getEndElement при MultipleSubmit давал, если я правильно понимаю, кнопки с одинаковыми функциями и стилем (меняется только name и color). Поэтому, пришлось расширить эту часть метода и дополнительно передать помимо onclick еще style и type (с проверкой, что они, вообще, есть в коллекции). Или как-то лучше можно сделать?

Форматирование сделал все, как написано в code style. Но при его применении поменялись относительно оригинала некоторые куски кода, к которым я даже не прикасался. Использую Intellij Idea.

2021-01-12 11:59 UTC, AlexMisha requested changes
Получается получше, оставил пару небольших замечаний.

> Форматирование сделал все, как написано в code style. Но при его применении поменялись относительно оригинала некоторые куски кода, к которым я даже не прикасался. Использую Intellij Idea.

Чтобы этого избежать, можно форматировать [только нужные строки](https://stackoverflow.com/a/63071292)

2021-01-12 11:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        List<Map<String, String>> data = Lists.newArrayList();
Элементов в списке будет 2, можно указать `capacity`

2021-01-12 11:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        buttonData1.put("name", getSubmitButtonName());
Хорошо бы вынести строки в константы

2021-01-12 11:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        Map<String, String> buttonData1 = Maps.newHashMap();
Хотелось бы увидеть более осмысленные названия, например `createButtonData`, `submitButtonData`

2021-01-12 11:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        return data;
Тогда уж `return Arrays.asList(buttonData1, buttonData2);` ?

2021-01-12 11:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/tag/FormTag.java
> +                    if (buttonData.containsKey("type")) {
Можно атрибуты, которые нельзя добавить через `Input.addAttribute` просто удалять из мапы (`remove` возвращает удаленное значение для ключа), а остальные добавлять через итерацию по `map.entrySet`

2021-01-12 19:09 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        List<Map<String, String>> data = Lists.newArrayList();
Учитывая предпоследнее замечание, эту строчку убрал. Теперь возвращаем сразу фиксированный List.

2021-01-12 19:12 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        buttonData1.put("name", getSubmitButtonName());
Добавил константы в FormTag.java

2021-01-12 19:12 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        Map<String, String> buttonData1 = Maps.newHashMap();
Переделал

2021-01-12 19:13 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/af/web/tag/BotListTag.java
> +        return data;
Сделал

2021-01-12 19:13 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/common/web/tag/FormTag.java
> +                    if (buttonData.containsKey("type")) {
Сделал. Только добавление атрибутов сделал через Map.forEach(). Внутри реализации forEach эта итерация и применена.

2021-01-12 19:15 UTC, hramovalexey commented
Исправил

2021-01-14 18:04 UTC, AlexMisha requested changes
Одно небольшое замечание, в остальном - ок

Подскажите, пожалуйста, как с вами связаться для обсуждения дальнейших задач? telegram/skype/email?

2021-01-14 18:04 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/tag/FormTag.java
> +                    if (buttonData.containsKey(ATTRIBUTE_TYPE)) {
Лишний вызов `containsKey`: можно сразу `remove`, а если `null`, то `Input.SUBMIT`

2021-01-15 06:49 UTC, hramovalexey commented on wfe-web/src/main/java/ru/runa/common/web/tag/FormTag.java
> +                    if (buttonData.containsKey(ATTRIBUTE_TYPE)) {
Исправил.

Связаться можно через телеграмм (+7 965 530 96 89). Но всё остальное перечисленное тоже есть, если удобнее там:
Skype hramovalexey
email hramovalexey@yandex.ru

2021-01-15 10:29 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:41 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-server/commit/9c5018314a2a21b84c3ffc1c4f160cbb7d359d38

2023-05-19 09:41 UTC, closed without merging