ChatSocket.handleMessage() refactoring
processtech/runawfe-free-server pull request #200
Opened 2021-01-01 14:13 UTC by CrimsonParade

Создан enum `MessageType`, содержащий все виды сообщений, кроме `nextStepLoadFile, stepLoadFile,  unblockOldMes`, 
т.к. для них нет хэндлеров (возможно, всё сломалось из-за этого, хотя я не понимаю, где может быть связь).
Для `MessageType` создан Jackson-десериализатор.
Создана спринг-конфигурация `ChatConfig`, в которой созданы мэп-бины: `handlerByMessageType` и `dtoByMessageType`.

Создан сервисный класс `ChatService`, в который инжектятся мэп-бины.
Хэндлеры достаются из `handlerByMessageType` по `messageType` (как мне кажется, для уменьшения связности, это лучше делать именно в сервисном классе).
`dtoByMessageType` используется для выбора нужного наследника `ChatDto` (возможно, преобразование можно как-то оптимизировать, но варианта без хардкода я пока не придумал).

Из `ChatDto` удалены `load()`, т.к. преобразование происходит в сервисном классе, и тип messageType изменен на Enum.
`ChatSocketMessageHandler` сделан абстрактным дженерик-классом от `<T extends ChatDto>`, в реализациях указаны соответсвующие наследники.
Из хэндлеров, за ненадобностью, удален `checkType()`, а сигнатура `handleMessage()` изменена, т.к. преобразование происходит в сервисном классе.

Сервисный класс покрыт тестами `ChatServiceTest`, в который импортируется `ChatConfig`.
Как мне кажется, использование Mockito в данном случае не требуется, ибо проверяется не то, вызывается ли метод, а правильный ли наследник возвращается, если я ошибаюсь, исправлю.

** В pom.xml добавлена зависимость на CGLIB, так как без неё Spring 3.1 не загружает конфигурацию из `@Configuration`-классов (пробовал деплоить без этой зависимости, проблема не исчезала)
** В `AddNewMessageHandler` добавлены `System.out.println()` только для проверки того, 
что бины не инжектятся (см. приложение), после решения проблемы они будут удалены.

______________________________________________________________________________________________________

Суть проблемы: по непонятной причине, бины не инжектятся ни в хэндлеры, ни в классы с логикой - вообще никуда.
Пытался создавать бины напрямую в хэндлерах (для выяснения причины), но тогда NPE падало в классах с логикой (не инжектились dao).
Судя по всему, либо контекст вообще не поднимается, либо в него по какой-то причине не попадают бины из xml-конфигураций (хотя я пытался создавать бины в классе-конфигурации, и они все равно не инжектились).
Второй день пытаюсь понять, что я сломал, но ничего так и не нашел.

В приложение добавил stack trace ошибки.
[log.txt](https://github.com/processtech/runawfe-free-server/files/5759013/log.txt)

2021-01-05 10:07 UTC, AlexMisha requested changes
В целом становится лучше, надо продолжать в том же духе

По комментарию:

> Создан enum MessageType, содержащий все виды сообщений,
кроме nextStepLoadFile, stepLoadFile, unblockOldMes, т.к. для них нет хэндлеров

Все равно стоит создать, пусть без хэндлеров, будем еще загрузку файлов рефакторить

> Из хэндлеров, за ненадобностью, удален checkType()

Метод нужен, чтобы заполнить map в конфигурации. Т.е. там будет двойной цикл: сначала по хэндлерам, затем для каждого хендлера ищем тот тип сообщения, который он принимает

> В текущей реализации не работает изменение сообщений из-за того, что при изменении зачем-то используется ChatEditMessageResponseDto (не использующееся больше нигде).
При попытке перекастовать его в ChatMessageDto, ожидаемо, падает ClassCastException.
Исправил эту странность, заменив ChatEditMessageResponseDto на ChatMessageDto, после чего редактирование сообщений заработало. Хотя это не было прописано в задании, мне показалось, что от исправления бага хуже не будет; если ошибаюсь - прошу прощения.

Окей, пусть будет. Надо будет еще потом пересмотреть наименования dto
Пока что лучше делать рефакторинг небольшими порциями, чтобы не зарыться в нем надолго

> В ChatSessionHandler достаточно много дублирующегося кода, может быть мне его также стоит отрефакторить?

Позже, отдельным тикетом

2021-01-05 10:07 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/ChatSocket.java
> +import javax.websocket.*;
Полагаю, слетели импорты, см. https://runawfe.org/rus/doc/DevelopersInfo#CodeStyle;

2021-01-05 21:30 UTC, CrimsonParade commented
Почитал про `@JsonTypeInfo`: возможно, нам больше подойдет `Id.CLASS`?
`Id.CLASS` генерируется самими Jackson'ом (в качестве значения передается fully-qualified class name), 
поэтому даже при добавлении/изменении наследников `ChatDto` не нужно будет изменять конфигурацию.
В случае с `id.NAME`, как я понял, нужно прописывать всех наследников в аннотации над суперклассом, что позволяет задавать значения вручную, но при добавлении/изменении наследников придется изменять и конфигурацию.
Мне кажется, в нашем случае использование `Id.CLASS` будет предпочтительнее, ибо чат находится на ранней стадии разработки, и конфигурация, вероятно, еще не раз изменится. 

В остальном - исправил замечания, но столкнулся с крайне странной проблемой.
После изменения `@JsonProperty` с `messType` на `messageType`, стала падать ошибка, возникающая из-за того, что в `message` параметр все еще называется `messType`. 
Первой гипотезой было, что сообщение генерируется каким-то необычным способом, 
но после рефакторинга в коде `messType` нигде не используется.
Та же ситуация и с переменной `@class`, она в сообщении также отсутствует.

Проблема, судя по всему, не в преобразовании, а где-то в хэндлерах, ибо если конвертировать любого наследника с помощью `convert()`, то получившийся Json содержит корректные `@class` и `messageType`.

![messTypeError](https://user-images.githubusercontent.com/70919069/103696975-4d9e7200-4fb0-11eb-9472-3614529d62ae.png)

![messTypeUsages](https://user-images.githubusercontent.com/70919069/103697233-a8d06480-4fb0-11eb-9fc6-32b7fdddd5e9.png)

2021-01-06 13:55 UTC, AlexMisha requested changes
> Почитал про @JsonTypeInfo: возможно, нам больше подойдет Id.CLASS?
Id.CLASS генерируется самими Jackson'ом (в качестве значения передается fully-qualified class name),
поэтому даже при добавлении/изменении наследников ChatDto не нужно будет изменять конфигурацию

Придется изменять js код, иначе атрибуту `@class` будет неоткуда взяться
`Id.CLASS` подходит для сценариев обмена сообщениями между двумя java системами с одинаковой моделью данных
Однако js код при таком подходе будет выглядеть не очень - там ведь будут полные названия классов

> Та же ситуация и с переменной `@class`, она в сообщении также отсутствует

Собственно об этом я и упомянул выше

> После изменения `@JsonProperty` с messType на messageType, стала падать ошибка, возникающая из-за того, что в message параметр все еще называется messType

Есть вероятность, что js закешировался. Можно попробовать обновить страницу ctrl + f5

2021-01-06 13:55 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
>  //@Interceptors({ SpringBeanAutowiringInterceptor.class })
Лишние комментарии просьба убрать

2021-01-06 13:55 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSocketMessageHandler.java
> +    boolean checkMessageType(MessageType messageType);
```suggestion
    boolean isSupports(MessageType messageType);
```

?

2021-01-06 13:55 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/service/MessageTypeServiceTest.java
> +    public static class ContextConfiguration {
Конфигурацию в тесте лучше не дублировать, а использовать "боевую"

2021-01-06 13:55 UTC, AlexMisha commented on wfe-core/pom.xml
> +			<artifactId>cglib</artifactId>
Просьба уточнить, действительно есть ли необходимость в этой зависимости в тестах?

2021-01-06 14:18 UTC, CrimsonParade commented on wfe-core/pom.xml
> +			<artifactId>cglib</artifactId>
Без CGLIB, как я понял, Spring 3.1 не загружает конфигурацию из `@Configuration`-классов. 
`"Starting with Spring 3.2, it is no longer necessary to add cglib as an explicit dependency."`
Что странно, вне тестового окружения все работает и без этой зависимости.

2021-01-06 14:23 UTC, CrimsonParade commented on wfe-core/src/test/java/ru/runa/wfe/chat/service/MessageTypeServiceTest.java
> +    public static class ContextConfiguration {
Пытался использовать "боевую" конфигурацию в тестах, но, по какой-то причине, спринг не подтягивает остальной контекст, из-за чего падает ошибка создания бина `List<ChatSocketMessageHandler>`.
Ищу, из-за чего это может происходить, но пока решения не найдено.

2021-01-06 16:24 UTC, CrimsonParade commented
Судя по всему, избежать еще одного поля в Json'e не получится, так как `@JsonTypeInfo `с любым `Id` использует отдельную переменную для сериализации/десериализации полиморфных типов. 
Изменил с `Id.CLASS` на `Id.NAME`, в качестве имени для типов использовал соответсвующие `messageType`.
В js для каждого типа сообщений добавил эту переменную и приравнял её к `messageType` (`type=messageType`). 
А имя не изменялось из-за кеша (очистил кеш и все заработало), премного благодарен за помощь, в эту сторону даже не думал.
Лишние комментарии удалил, по поводу тестов ответил в реплаях.

2021-01-12 12:17 UTC, AlexMisha requested changes

2021-01-12 12:17 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/config/ChatConfig.java
> +                                                                                        List<ChatDto> dtos) {
dto бинами делать точно не надо, это же короткоживущие объекты
Лучше сделать бин в конфигурации, который вернет список `List<Class<? extends ChatDto>>`. Список заполнить вручную

2021-01-12 12:17 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSocketMessageHandler.java
> +    boolean isSupports(Class<? extends ChatDto> messageType);
```suggestion
    boolean isSupports(Class<T> messageType);
```
По идее так даже правильнее

2021-01-12 12:17 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/service/MessageTypeServiceTest.java
> +    public static class ContextConfiguration {
Надо добавить `@ComponentScan` в `ChatConfig` на пакет, в котором хэндлеры лежат

2021-01-13 19:26 UTC, AlexMisha requested changes

2021-01-13 19:26 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/config/ChatConfig.java
> +    public Map<Class<? extends ChatDto>, ChatSocketMessageHandler> handlerByMessageType(List<ChatSocketMessageHandler> handlers) {
`ChatSocketMessageHandler` не указан generic. Лучше указать <? extends ChatDto>. Если тут будут проблемы с передачей аргумента в `isSupports`, то можно в `isSupports` вернуть `? extends ChatDto` вместо `T`

2021-01-14 13:22 UTC, AlexMisha approved these changes
:+1:

2021-01-14 13:22 UTC, merged