rm2021 Рефакторинг ChatSocket.uploadFile:
processtech/runawfe-free-server pull request #204
Opened 2021-01-12 19:15 UTC by insoftjla

* ChatSocket:
    * uploadFile() - собирает файл по частям(в случае любой ошибки в процессе сборке выбрасывает исключение UploadChatFileException), сохраняет его и отвечает клиенту;
    * handleMessage() - убрана конструкция try catch чтобы обрабатывать ошибки в методе onError();
    * onError() - добавлена обработка исключений;
 * ChatSessionHandler - добавлены методы:
    * addFile() - добавляет новый объекта ChatMessageFile в сессию
    * nextFileLoad() - готовит сессию для получения следующего файла и посылает клиенту сообщение о готовности и что файл загружен;
    * loadFileError() - готовит сессию для получения следующего файла и посылает клиенту сообщение о готовности и что файл не загружен;
    * messageError() - очищает userProperties и отправляет клиенту статус error с сообщением.
 * AddNewMessageHandler - добавлена проверка размера файлов;
 * chat.js - проверка статуса сообщения (messType = "error");
 * ChatMessageFile - добавлен конструктор;
 * JSONMessageStatus - генерирует JSON строку с состоянием;
 * Созданы исключения ChatException, MaxChatFileSizeExceedException, UploadChatFileException.

2021-01-14 13:58 UTC, AlexMisha reviewed
В целом направление изменения кода мне нравится

Просьба учесть доработки в master1461. Теперь можно для каждого хэндлера сделать свою dto

2021-01-14 13:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/ChatException.java
> +public class ChatException extends InternalApplicationException {
Это у нас control flow исключения будут, поэтому им не нужно заполнение stack trace
Лучше наследовать от `RuntimeException`. Пока что достаточно одного конструктора с параметром `message` и использованием [полного родительского конструктора](https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html#RuntimeException(java.lang.String,%20java.lang.Throwable,%20boolean,%20boolean)) `super(message, null, false, false)`

2021-01-14 13:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/JSONMessageStatus.java
> +public class JSONMessageStatus {
См. доработки по задаче 2020. По идее этот класс теперь не нужен

2021-01-14 13:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/MaxChatFileSizeExceedException.java
> +    private static final String MESSAGE = "File exceeds the maximum size";
Думаю, имеет смысл завести в `ChatException` 2 строковых поля: `code` и `message`. В `code` передавать код ошибки, чтобы клиент понимал, как ему реагировать, а в `message` - локализованное сообщение об ошибке, если оно предусмотрено для исключения

2021-01-14 13:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +    // создаёт объект ChatMessageFile и добавляет его в userProperties
Комментарии только на английском

2021-01-14 13:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +    // дублирование кода, взято из EndLoadFilesMessageHandler
Если дублирование, то имеет смысл завести `ChatSessionUtils` и вынести метод в статику

2021-01-14 13:58 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/ChatSocket.java
> +    public void onError(Throwable error, Session session) {
Для обработки ошибок имеет смысл завести специальный бин вроде `ChatErrorHandler` или `ChatExceptionTranslator` и делегировать обработку ошибок ему. Тут оставить только логирование

2021-01-14 13:58 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/ChatSocket.java
> +    public void uploadFile(ByteBuffer buffer, boolean last, Session session) throws IOException {
Аналогично, логику по загрузке файлов хотелось бы увидеть в отдельном бине, чтобы не загружать сокет

2021-01-19 09:31 UTC, AlexMisha requested changes

2021-01-19 09:31 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatErrorMessageDto.java
> +    public ChatErrorMessageDto(String message) {
Лучше с аннотациями lombok: `@AllArgsConstrustor, @NoArgsConstructor, @Getter, @Setter`
И соответственно геттеры/сеттеры не нужны, jackson итак умеет

2021-01-19 09:31 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatNewMessageDto.java
> +    public Map<String, byte[]> getFiles() {
Тут тоже геттеры/сеттеры не нужны

2021-01-19 09:31 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatNewMessageDto.java
> +    public void setFiles(Map<String, Object> map){
В dto логики быть не должно. Лучше реализовать deserializer

2021-01-19 09:31 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/ChatSocket.java
> +import javax.websocket.*;
Съехали импорты

2021-01-19 09:31 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +    public static final long CHAT_MAX_MESSAGE_SIZE = (long) (1024 * 1024 * 10 * 1.33);
`DEFAULT_CHAT_MAX_MESSAGE_SIZE` ?

2021-01-19 09:31 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +        return RESOURCES.getLongProperty("chat.max.message.size", 0);
И тут соответственно нужно использовать значение по умолчанию - `DEFAULT_CHAT_MAX_MESSAGE_SIZE`

2021-01-19 09:31 UTC, AlexMisha commented on wfe-web/src/main/webapp/js/chat.js
> +const sendToChatNewMessage = (message) => {
К сожалению, не представляется возможным использовать такие фичи js, как async/await, const, let и пр., т.к. у нас есть клиенты, которые завязаны на chrome v41. Соответственно нужно сверять с [таблицей совместимости](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/let#%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0_%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0%D0%BC%D0%B8)

2021-01-19 09:31 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
> +        ChatMessageDto chatMessageDto;
Спусти, пожалуйста, поближе к использованию

2021-01-21 08:39 UTC, AlexMisha requested changes

2021-01-21 08:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/coder/ChatDtoBinaryDecoder.java
> +            throw new DecodeException(byteBuffer, e.getMessage());
В конструкторе можно еще передать `Throwable cause`. Лучше это сделать (передать io exception)

2021-01-21 08:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatMessageDto.java
> +    @JsonProperty("fileArray")
```suggestion
    @JsonProperty("files")
```
?

2021-01-21 08:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatMessageDto.java
>      private boolean mentionedFlag = false;
```suggestion
    private boolean isMentioned = false;
```
В java конвенциях обычно так принято. Для `coreUserFlag` и `old` аналогично. Предлагаю заодно поправить

2021-01-21 08:39 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +        return RESOURCES.getIntegerProperty("chat.max.message.size", DEFAULT_CHAT_MAX_MESSAGE_SIZE);
Лучше указать единицы измерения:
```suggestion
        return RESOURCES.getIntegerProperty("chat.max.message.size.bytes", DEFAULT_CHAT_MAX_MESSAGE_SIZE);
```

2021-01-21 08:39 UTC, AlexMisha commented on wfe-web/src/main/webapp/js/chat.js
> +	files.forEach(file => {
Стрелочные функции в chrome 41 тоже не поддерживаются :(

2021-01-21 08:39 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +    public static int getMaxMessageSize() {
И стоит как-нибудь указать, что это максимальный размер сообщения для чата. Например, `getMaxChatMessageSize`

2021-01-21 08:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatNewMessageDto.java
> +    private Map<String, byte[]> files;
deserializer еще в разработке или jackson сам разобрался, как это поле обработать?

2021-01-21 17:32 UTC, insoftjla commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatNewMessageDto.java
> +    private Map<String, byte[]> files;
Да, jackson сам понимает.

2021-01-22 09:21 UTC, AlexMisha approved these changes
:+1:

2021-01-22 09:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatNewMessageDto.java
> +    private Map<String, byte[]> files;
Только, наверное, он сам из Base64 не декодирует
Похоже, без декодера не обойтись

2021-01-22 09:48 UTC, merged