Fixing line thickness of active processes and tuning performance
processtech/runawfe-free-server pull request #205
Opened 2021-01-18 23:13 UTC by msin87

- Исправлено: 

> При клике на id процесса в задании надо сделать так, чтобы на открывшейся схеме композиция (внутренний подпроцесс), в которой находится точка управления, породившая задание, была выделена жирным зеленым контуром.
> Не работает.
> Если в БП более одной композиции выделяет жирным похоже запущенную самой последней, независимо от того из какого задания в списке перешли по ссылке в экземпляр БП.
> Уточнение:
> - композиция в которой находится точка управления, породившая задание (с которого пришли на схему), была выделена жирным зеленым контуром, а все остальные композиции, в которых находятся точки управления (не породившие задание, с которого пришли на схему) были выделены жирным черным контуром.
> - если на схему пришли не через задание, то все композиции, в которых находятся точки управления, были выделены жирным черным контуром.
> 

- Реализован метод `GraphImageBuilder::getActiveNodesId`. Алгоритм выбора активной ноды остался прежним: ищется последняя запись типа `NodeEnterLog`, и если она есть, то эта нода считается активной. Далее, ищется последняя запись с типом `NodeLeaveLog`, то есть откуда был выход. И если выход был произведен из `NodeType.PARALLEL_GATEWAY`, то берется фигура с id `lastLeaveLog.getNodeId()` , то есть именно того шлюза, откуда был выход. В найденном шлюзе берутся все переходы на другие фигуры, и смотрятся `id` этих фигур. Соответственно, эти фигуры и будут активным, т.к. параллельный шлюз производит одновременный запуск подсоединенных к нему процессов. 
Если потребуется иная логика для других типов элементов, то ее можно добавить в switch-case. 
![screenshot](https://user-images.githubusercontent.com/8974463/104970244-db8c4b00-59fb-11eb-9ce4-991c6797acc3.jpg)
- `GraphImageBuilder::createDiagram`. Немного разбил код на методы. Но необходим дальнейший глубокий рефакторинг, иначе добавление новых фич будет затруднительно

. Нужно уменьшать связность кода. SOLID, и только SOLID.

- `EditUserTypeList:: getTemplateValue` Оптимизирована замена символов (быстрее в ~9 раз).

2021-01-19 10:39 UTC, AlexMisha requested changes
Судя по скрину, то, что сделано - не совсем то, что требуется. Требуется, чтобы при переходе из списка задач подкрашивалась зеленым та композиция, в которой эта задача активна, а остальные композиции - черным.

Из постановки:

> композиция в которой находится точка управления, породившая задание (с которого пришли на схему), была выделена жирным зеленым контуром, а все остальные композиции, в которых находятся точки управления (не породившие задание, с которого пришли на схему) были выделены жирным черным контуром

2021-01-19 10:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/execution/logic/ExecutionLogic.java
> +            return builder.createDiagram(process, processLogs, getAbstractFigureFactory(processDefinition.getDeployment().getLanguage()));
Не совсем понимаю, зачем переносить то, что относится к ui, в сервисный слой?

2021-01-19 10:39 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/graph/image/GraphImageBuilder.java
> +    private boolean isActiveNode(String nodeId, ProcessLogs logs) {
Насколько вижу, метод вызывается в цикле. Получается, цикл по нодам, затем по логам и затем по id нод? Т.е. порядка O(n^3). На больших схемах могут появиться дополнительные лаги

2021-01-19 19:17 UTC, msin87 commented on wfe-core/src/main/java/ru/runa/wfe/execution/logic/ExecutionLogic.java
> +            return builder.createDiagram(process, processLogs, getAbstractFigureFactory(processDefinition.getDeployment().getLanguage()));
```java
GraphImageBuilder builder = new GraphImageBuilder(processDefinition);
builder.setHighlightedToken(highlightedToken);
return builder.createDiagram(process, processLogs);
```
В сервисном слое уже есть то, что относится к UI. Перенос был сделан для возможности реализации дальнейшего уменьшения связности кода. Вообще, надо хорошо подумать как реализовать MVC здесь.

Дальше пойдут мысли в слух.

Как я понял, `ExecutionServiceBean` служит контроллером. Тогда за контроллером должен стоять фасад или модель. `ExecutionLogic` можно было бы назвать фасадом, если бы поведение метода `getProcessDiagram` точно соответствовало бы его названию. `ExecutionLogic` в MVC должно быть M, а между контроллером и моделью можно поместить фасад. Но это все из разряда вечных споров. Но все же, `getProcessDiagram` должен принимать на вход `Process` и возвращать `Diagram`, ну или `getProcessImageRawBytes`. 

Дальше...
https://github.com/processtech/runawfe-free-server/blob/9e391665190a3dfa3a1d70273c6cfcb0cf95692e/wfe-core/src/main/java/ru/runa/wfe/execution/logic/ExecutionLogic.java#L252
бросает `AuthorizationException` . Данную логику очень хочется вынести на уровень выше. Почему `getProcessDiagram` еще отвечает и за проверку разрешений? Вероятно, это должно делаться на уровне контроллера:
```java
boolean isAllowed = ... ;
if (!isAllowed)
 throw new AuthorizationException();
return executionLogic.getProcessImageRawBytes(....);
``` 
А вообще, надо посмотреть в сторону  : 
https://www.baeldung.com/role-and-privilege-for-spring-security-registration 
Возможно не придется изобретать велосипед. 

https://github.com/processtech/runawfe-free-server/blob/9e391665190a3dfa3a1d70273c6cfcb0cf95692e/wfe-core/src/main/java/ru/runa/wfe/execution/logic/ExecutionLogic.java#L256
`Task` используется только лишь для того, чтобы определить `Token`. Мне кажется было бы прекрасным вытащить всё общение с БД выше, в фасад. Тем, более, нарушается принцип единственной ответственности, метод же носит название `getProcess...` , но не `getProcess..byPermissions...byTask...byProcessLogs`. 
И очень хочется разделить `ExecutionLogic` на две части, одна из которых - `DiagramModel`. А дальше - можно еще выделить логику от туда, и все это будет моделями. 

Будущая модель `DiagramModel`  должна зависеть от `GraphImageBuilder` и `GraphHistoryBuilder` для удобства тестирования, и для возможных дальнейших подмен реализаций. 

Я не настаиваю. Я просто рассуждаю. Ведь то, что есть мне не нравится из-за имеющегося опыта поддержки и доработки подобных приложений. (на nodejs). 
Оцени каждую идею, и вообще всё видение в целом. В том числе и переход на React, ведь есть классные либы для js, которые рисуют flowchart'ы. Даже если беспокоят уязвимости в них - всегда можно реализовать всё самому. Canvas в HTML довольно быстро работает, вот пример: 
https://www.cssscript.com/demo/flowchart-diagram/ 
При помощи React (или Angular, или...) всю разработку можно будет разделить на две части. бэк и фронт.
Сейчас же при малейшем изменении где-либо в бэке, пересобирается и фронт. 
Фронт должен сам строить фигуры, фронт должен иметь набор фигур, независящий от бэка. Это все очень легко делается.. да всё в том же React. Делаются отдельные компоненты и всё. И эти компоненты очень удобно тестировать. Подумай над этим. Уверен, что если поднатужиться, то получится замечательный гибкий фронт, с которым будет очень легко работать как и пользователю, так и разработчику.

2021-01-19 19:19 UTC, msin87 commented on wfe-core/src/main/java/ru/runa/wfe/audit/ProcessLogs.java
> +import java.util.*;
Благодарю. А то запрашивал соглашения по код стайлу, так и не получил ответа.

2021-01-19 19:23 UTC, msin87 commented
> 
> 
> Судя по скрину, то, что сделано - не совсем то, что требуется. Требуется, чтобы при переходе из списка задач подкрашивалась зеленым та композиция, в которой эта задача активна, а остальные композиции - черным.
> 
> Из постановки:
> 
> > композиция в которой находится точка управления, породившая задание (с которого пришли на схему), была выделена жирным зеленым контуром, а все остальные композиции, в которых находятся точки управления (не породившие задание, с которого пришли на схему) были выделены жирным черным контуром

С третьей итерации вроде бы понял суть проблемы. Как я понял сейчас: при выборе из списка задач нужно подсветить именно ту композицию (при отображении всей диаграммы), на которую был клик. Композиция - это некий элемент диаграммы, который включает в себя другие элементы.

2021-01-19 19:29 UTC, msin87 commented on wfe-core/src/main/java/ru/runa/wfe/graph/image/GraphImageBuilder.java
> +    private boolean isActiveNode(String nodeId, ProcessLogs logs) {
Данный цикл среди других трёх циклов... в бочке мёда уже и так много дёгтя. Ложечка-другая там не помешает 😄 . На самом деле - мне немного непонятно зачем там столько циклов? Ведь `AbstractFigure` уже имеет внутри информацию о связях в `Node`. Можно ли только на основе `Node` построить логику?

2021-01-20 14:43 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/execution/logic/ExecutionLogic.java
> +            return builder.createDiagram(process, processLogs, getAbstractFigureFactory(processDefinition.getDeployment().getLanguage()));
> В сервисном слое уже есть то, что относится к UI. Перенос был сделан для возможности реализации дальнейшего уменьшения связности кода.

Пока что не понимаю, как перенос ответственности за создание figure factory на уровень выше поможет уменьшить связанность кода. Я согласен, что это не должна быть ответственность билдера, но и сервис для этого не подходит.

> Вообще, надо хорошо подумать как реализовать MVC здесь

RunaWFE - не совсем классическое web MVC приложение. Руна - прежде всего движок бизнес-процессов, т.е. api provider. У нас есть клиенты, которые пользуются в том числе ejb api и soap api. В данной части системы руна строит статичное представление графа исполнения бизнес-процесса в определенный момент времени. Если неожиданно переложить ответственность за построение графа на клиентов из-за того, что у фронта должен быть свой набор фигур, независящий от бэка, то мы сломаем api, клиенты будут недовольны.

> Но все же, getProcessDiagram должен принимать на вход Process и возвращать Diagram, ну или getProcessImageRawBytes

Навязывать клиентам свое представление картинки тоже неприемлемо, пусть клиенты сами решают, как они будут отображать картинку своим пользователям.

> бросает AuthorizationException . Данную логику очень хочется вынести на уровень выше. Почему getProcessDiagram еще отвечает и за проверку разрешений?

`getProcessDiagram` не отвечает за проверку разрешений, он делегирует это `PermissionDao`. Вынести выше не всегда представляется возможным. Например, см. метод `getProcessSwimlanes`: при получении каждой из ролей необходимо дополнительно проверить, есть ли у пользователя права на чтение исполнителя. Если вынести выше, то придется весь метод в сервис переносить.
Кроме того, для переноса проверок полномочий на уровень выше потребуется довольно объемный рефакторинг по всему проекту, выгода от больших трудозатрат не совсем понятна.

> А вообще, надо посмотреть в сторону :
https://www.baeldung.com/role-and-privilege-for-spring-security-registration
Возможно не придется изобретать велосипед.

Проект довольно старый (~ 2004 год). Тогда spring-security возможно еще и не было, а если и был, то не самый популярный вариант. Опять же рефакторинг трудоемкий, а выгода не ясна.

> Task используется только лишь для того, чтобы определить Token. Мне кажется было бы прекрасным вытащить всё общение с БД выше, в фасад

Выражаясь терминами современной архитектуры, классы *Logic - это сервисы, а *Service - фасады. Сервисы обычно используют несколько DAO, фасады - несколько сервисов. С этой точки зрения в проекте все более менее корректно

> Тем, более, нарушается принцип единственной ответственности, метод же носит название getProcess... , но не getProcess..byPermissions...byTask...byProcessLogs

`by...` обычно означает, что будет передан аргумент, по аналогии со spring-data.
`byPermissions` - коллекция permissions в метод не передается. Это было бы странно.
`byTask` - да, возможно стоило бы разделить на несколько методов byTask, byTaskAndChildProcess и т.д. Но, как можно заметить, в проекте прослеживается правило соответствия сигнатуры методов сервиса сигнатуре методов *Logic. Это общая стилистика проекта, так исторически сложилось.
`byProcessLogs` - это деталь реализации. Пользователя не должно волновать, как будет строиться диаграмма.

> И эти компоненты очень удобно тестировать. Подумай над этим. Уверен, что если поднатужиться, то получится замечательный гибкий фронт, с которым будет очень легко работать как и пользователю, так и разработчику.

На данный момент уже ведутся работы по разработке нового UI. Если интересно, то можем подключить к разработке после завершения этой задачи.

2021-01-20 14:46 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/graph/image/GraphImageBuilder.java
> +    private boolean isActiveNode(String nodeId, ProcessLogs logs) {
Можно, но я предлагаю для начала ограничиться реализацией конкретно поставленной задачи

2021-01-20 14:50 UTC, AlexMisha commented
> С третьей итерации вроде бы понял суть проблемы. Как я понял сейчас: при выборе из списка задач нужно подсветить именно ту композицию (при отображении всей диаграммы), на которую был клик. Композиция - это некий элемент диаграммы, который включает в себя другие элементы.

Да, или другими словами: нужно подсветить ту композицию, которой принадлежит выбранная из списка задача.

В системе существует 2 вида подпроцессов: внутренний (встроенный, embedded, композиция) и внешний. Определение внутреннего существует только в рамках родительского. Внешний - это самостоятельный процесс, который по ссылке запускается из родительского. Подробнее в [документации](https://runawfe.ru/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F2)

2021-01-21 15:52 UTC, msin87 commented
> 
> 
> > С третьей итерации вроде бы понял суть проблемы. Как я понял сейчас: при выборе из списка задач нужно подсветить именно ту композицию (при отображении всей диаграммы), на которую был клик. Композиция - это некий элемент диаграммы, который включает в себя другие элементы.
> 
> Да, или другими словами: нужно подсветить ту композицию, которой принадлежит выбранная из списка задача.
> 
> В системе существует 2 вида подпроцессов: внутренний (встроенный, embedded, композиция) и внешний. Определение внутреннего существует только в рамках родительского. Внешний - это самостоятельный процесс, который по ссылке запускается из родительского. Подробнее в [документации](https://runawfe.ru/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F2)

Еще раз, так?
![s1](https://user-images.githubusercontent.com/8974463/105375190-9180b080-5c19-11eb-99bb-134dbe6e7b48.jpg)
![s2](https://user-images.githubusercontent.com/8974463/105375336-b1b06f80-5c19-11eb-8fe6-af97ef63ff62.jpg)

2021-01-22 10:31 UTC, AlexMisha commented
Да, с толстой рамкой только тот, которому принадлежит задача, по которой кликнул пользователь.
Но в постановке есть еще уточнения:

> - композиция в которой находится точка управления, породившая задание (с которого пришли на схему), была выделена жирным зеленым контуром, а все остальные композиции, в которых находятся точки управления (не породившие задание, с которого пришли на схему) были выделены жирным черным контуром.
> - если на схему пришли не через задание, то все композиции, в которых находятся точки управления, были выделены жирным черным контуром.

2021-01-22 11:40 UTC, msin87 commented
`композиция в которой находится точка управления, породившая задание (с которого пришли на схему), была выделена жирным зеленым контуром, а все остальные композиции, в которых находятся точки управления (не породившие задание, с которого пришли на схему) были выделены жирным черным контуром.`

`была выделена` - это понимать как "нужно, чтобы была выделена", или "была выделена, нужно чтобы не была выделена"?

Аналогично и здесь:
`если на схему пришли не через задание, то все композиции, в которых находятся точки управления, были выделены жирным черным контуром.`

2021-01-23 22:50 UTC, msin87 commented
Поведение с жирными зелеными рамками исправлено. 
Требуется уточнение насчет https://github.com/processtech/runawfe-free-server/pull/205#issuecomment-765342576

2021-01-27 13:21 UTC, AlexMisha commented
Выражения вида "была выделена" нужно трактовать, как "нужно, чтобы была выделена".

> Можно без терминологии "породившая, точка управления..."? Просто конкретно что нужно. Четко и ясно. Что должно быть на экране.

Это предметная область проекта, которая прямо относится к исполнению бизнес-процессов. По-другому выражаться в контексте предметной области довольно сложно. Но попробую на пальцах:

Как я упоминал ранее, в системе есть 2 типа дочерних процессов: внешний и внутренний (композиция). В рамках данной задачи нас интересует только композиция.
При запуске бизнес-процесса создается т.н. "точка управления" - указатель на текущий активный узел бизнес-процесса. Количество точек управления может увеличиваться и уменьшаться в зависимости от наличия узлов fork/join на графе бизнес-процесса.
Если точка управления находится в композиции, то композиция должна быть подкрашена жирным черным контуром.

Узлами в бизнес-процессе могут быть в том числе задания. Активное задание - то, на которое на данный момент "указывает" точка управления. Активные задания выводятся на странице "Список заданий". Считается, что задание принадлежит композиции, если узел задания принадлежит графу композиции. В таблице списка заданий есть столбец "Номер экземпляра процесса", в котором выводится номер процесса, при клике на который пользователь попадает на граф бизнес-процесса. Следствие предыдущего абзаца: если в композиции есть активное задание, то композиция должна быть подкрашена жирным черным контуром.
Но в рамках обсуждаемой задачи требуется реализовать еще один вид подкрашивания композиции - жирным зеленым контуром.

Условия подкрашивания композиции жирным зеленым контуром:
1. Переход на граф бизнес-процесса был осуществлен со страницы "Список заданий" путем нажатия на ячейку в столбце "Номер экземпляра процесса". Ряд, в котором находится кликнутая ячейка, будем называть "выбранное задание".
2. Выбранное задание принадлежит композиции.

И просьба проверить PR, в нем почему-то 219 измененных файлов.

2021-02-24 11:16 UTC, closed without merging