Sessions refactoring
processtech/runawfe-free-server pull request #208
Opened 2021-01-25 13:42 UTC by CrimsonParade

* Тип `sessions` изменен с `CopyOnWriteArraySet` на `ConcurrentHashMap`; 
 удалена `onlyNewMessagesSessions` и связанная с ней логика;
 удалены неиспользующиеся методы и переменная;

* Переработано добавление сессий: 
при наличии у пользователя сессии, новая не добавляется, а заменяет собой предыдущую; 
при замене сессии в логи пишется warn;

* Сигнатура `sendNewMessage()` изменена - в качестве параметра передается `mentionedActors`, а не `mentionedExecutors`
(в текущей реализации `mentionedActors` вычислялись дважды: 
в `ChatSessionHandler.sendNewMessage()` и `AddNewMessageHandler.handleMessage()`)

* `processId` вынесен в `ChatDto`
 В хэндлерах используется `processId` из dto, а не из атрибутов сессии
 Из `ChatSessionHandler.sendToChats()` удалена проверка на то, равны ли `processId` сессии и dto

* Из `ChatSocketConfigurator` удалено добавление лишних атрибутов

* Немного причесан `ChatInitializeAjax`

* В `chat.js` и `common.js` из `WebSocketUrl` удален параметр `type`, отвечавший за тип сессии

2021-01-25 15:28 UTC, AlexMisha requested changes

2021-01-25 15:28 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        for (Session session : sessions.values()) {
Тут получается O(n) от количества сессий, а не от `mentionedActors`. Теряем преимущество от использования мапы.
Но при этом в `mentionedActors` приходят только те, кто отмечен через `@`, если я правильно понимаю. На мой взгляд стоит потом в `mentionedActors` передавать сразу всех получателей из хэндлера. Тогда можно будет от лишних флажков избавиться в dto.

А тут пока что итерироваться по списку `mentionedActors`, для каждого вытаскивать из мапы сессию и отправлять сообщение.
При этом желательно вынести физическую отправку сообщения в другие классы, используя "каноническую" форму паттерна chain of responsibility.

В чем суть:
В дальнейшем планируется добавить email уведомления о поступивших сообщениях. Но email отправлять не надо, если у пользователя есть активная сессия. Код работы с отправкой email'ов довольно громоздкий, поэтому хотелось бы его вынести в отдельный компонент, да и не ответственность это хэндлера сессий.

Как я вижу реализацию:
Заводим 2 компонента `SessionMessageSender` и `MailMessageSender` (реализуют общий интерфейс). В `ChatSessionHandler` инжектим по интерфейсу и qulifier'у первый, а в `SessionMessageSender` - второй.
Если есть активная сессия, то отрабатывает только первый, если нет - то первый делегирует исполнение второму.
В `MailMessageSender` можно пока что заглушку поставить с логированием

2021-01-25 15:28 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        sendToChats(dto, processId, null, new HashSet<>(), false);
```suggestion
        sendToChats(dto, processId, null, Collections.emptySet(), false);
```
?

2021-01-25 15:28 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> -        MessageForCloseChatDto messageForCloseChat = new MessageForCloseChatDto();
`MessageForCloseChatDto` вроде больше нигде не используется, можно удалить

2021-01-25 15:28 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +    private final ConcurrentHashMap<Long, Session> sessions = new ConcurrentHashMap<>();
Думаю, стоит ориентироваться на ~ 100-300 активных сессий
Т.е. надо поправить `initialCapacity`, чтобы постоянных resize не было

2021-01-26 09:30 UTC, CrimsonParade commented
* Поправил замечания

* Добавил интерфейс `MessageSender` и две имплементации: `SessionMessageSender` и `MailMessageSender`:
в `SessionMessageSender` скопирована логика отправки сообщения, с удалением флагов `IsMentioned` и `IsPrivate`;
в `MailMessageSender` добавлена заглушка;
`MailMessageSender` инжектится по qualifier'у в `SessionMessageSender`, `SessionMessageSender` - в хэндлер;
`ChatSessionHandler` изменен в связи с добавлением `MessageSender`;

* Причесал `AddNewMessageHandler`: 
оставил `TODO` на генерацию списка получателей для неприватных сообщений;
разбил один большой `handleMessage()` на небольшие логические методы;
вынес из `generateMentionedExecutors` несколько методов;
переименовал некоторые переменные и методы для улучшения читаемости;

2021-01-26 11:42 UTC, AlexMisha requested changes

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/MailMessageSender.java
> +@Component("mailMessageSender")
Если не ошибаюсь, спринг такое имя бину сделает автоматически

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/MessageSender.java
> +    void handleMessage(Session session, ChatMessageDto dto) throws IOException;
`throws IOException`
Получается, если отправка одного из сообщений упадет, то все получатели после тоже не получат сообщение?

И судя по коду реализаций, `session` может быть null. Соответственно лучше это подчеркнуть в сигнатуре - сделать аргумент `Optional<Session>` и поставить его после dto.

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/SessionMessageSender.java
> +            session.getBasicRemote().sendText(dto.convert());
Исключение надо бы перехватывать

Для этого компонента уже можно написать тесты с моками на 3 ситуации:
1. Сессия не null, отправка успешная.
2. Сессия не null, отправка - исключение.
3. Сессия null, делегирование в другой sender

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
> +    private ChatMessage generateChatMessageByDto(ChatNewMessageDto dto, User user) {
Если взялись за рефакторинг хэндлера, то надо соблюдать SOLID. Этот метод стоит вынести в отдельный converter компонент

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
> +        newMessage.setCreateDate(new Date(Calendar.getInstance().getTime().getTime()));
Можно просто `new Date()`

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
> -    void searchMentionedExecutor(Collection<Executor> mentionedExecutors, ChatMessage newMessage, String[] loginsPrivateTable, User user,
`searchMentionedExecutor` предлагаю оставить, как есть, но вынести в отдельный компонент.

В текущей реализации проще читается алгоритм, соответственно его проще будет в дальнейшем оптимизировать

Единственное - можно возвращать сразу `Set<Actor>`, чтобы не конвертировать лишний раз нигде

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/AddNewMessageHandler.java
> -        // mentioned executors are defined by '@user' pattern
Комментарий тоже лучше оставить, но вынести в javadoc к методу

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        User user = (User) session.getUserProperties().get("user");
`(User) session.getUserProperties().get("user")` повторяется часто
Стоит завести `ChatUtils` и соответствующий утилитный метод

2021-01-26 11:42 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dto/ChatMessageDto.java
> -    private boolean isMentioned = false;
Вижу в js использования свойства. Тоже почистить стоит

2021-01-27 13:59 UTC, AlexMisha requested changes

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/SessionMessageSender.java
> +                log.error("The message was not sent", e);
Предпочтительнее сообщение вида An error occured while sending message to ${name пользователя}
И тогда надо на почту уведомление отсылать

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        User user = getUser(session);
На мой взгляд в "боевых" классах лучше писать полностью `ChatUtils.getUser`, так понятнее при ревью.
Импортировать статический метод можно в тестах, например, `Mockito.mock` заменять на `mock`

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        if (sessions.replace(userId, session) != null) {
Старую сессию при этом надо закрывать. Думаю, со статусом `CLOSED_ABNORMALLY`

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/utils/ChatUtils.java
> +public class ChatUtils {
`ChatSessionUtils` ?

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/utils/DtoConverter.java
> +public class DtoConverter {
Если ожидается, что тут будет много конвертирующих методов, то надо во множественном числе `DtoConverters`.
Если один, то как-то вроде `ChatNewMessageDtoToChatMessageConverter` и метод просто `convert`

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +@ContextConfiguration
В данном случае лучше все зависимости замокать. В `SessionMessageSender` зависимости можно передать через конструктор

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    Session session = mock(Session.class);
Тоже `private`. И можно вместо инициализации поставить аннотацию `@Mock`

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    public void correctCase() throws IOException {
Вроде бы уже не должны бросать `IOException`.

2021-01-27 13:59 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    public void incorrectDto() throws IOException {
Имена тестов лучше писать примерно так:
givenIncorrectDto_then${ожидаемый результат}.

Например, для теста сценария
1. Попытка отправить сообщение.
2. Remote бросил исключение.
3. Делегирование MailMessageSender.

Название будет выглядеть примерно так - `givenSendError_thenSendDelegated`.
И в тесте сначала надо сделать подготовки вида Mockito.when(вызов метода).thenThrow(исключение), затем вызвать метод и после этого проверить, что мок-делегат вызвался verify(mock).вызов метода.

2021-01-27 13:59 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/web/ChatSocket.java
> +import static ru.runa.wfe.chat.utils.ChatUtils.getUser;
Тут тоже лучше использовать полное имя без static импорта

2021-01-27 18:00 UTC, CrimsonParade commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    public void correctCase() throws IOException {
Компилятор на `verify(basic).sendText()` ругается (`sendText()` бросает `IOException`).

2021-01-27 19:14 UTC, AlexMisha requested changes

2021-01-27 19:14 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +                        "Replace" + user.getName() + "'s session");
После Replace пробел нужен :)

2021-01-27 19:14 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +                CloseReason closeReason = new CloseReason(CloseReason.CloseCodes.getCloseCode(1006),
Есть константа в `CloseReason.CloseCodes`

2021-01-27 19:14 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +import static org.mockito.Mockito.*;
Импорты опять слетели

2021-01-27 19:14 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        MockitoAnnotations.initMocks(this);
Можно с помощью mockito runner'а. `@RunWith` над классом и погуглить название runner'а

2021-01-27 19:14 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        when(incorrectDto.convert()).thenThrow(new RuntimeException());
Не, эти 2 строчки с `when` должны относиться к конкретным тестам. И протестировать нужно не ошибку конвертации, а ошибку отправки сообщения в сессию

2021-01-28 10:36 UTC, AlexMisha requested changes
Для примера написал сам тесты, а то объяснять сложно. Посмотри, впредь примерно так стоит делать.

И посмотри еще, пожалуйста, `SwitchChatsInitializeAjax` там осталось использование `isMentions`. Возможно еще где-то в сервисах

2021-01-28 10:36 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    @Test(expected = RuntimeException.class)
Исключение наружу пролезть не должно. Иначе отправка последующих сообщений упадет. И бросать надо `IOException`.

2021-01-28 13:13 UTC, AlexMisha approved these changes
:+1:

2021-01-28 13:13 UTC, merged