Option  show only basic user groups  was added
processtech/runawfe-free-server pull request #211
Opened 2021-01-28 14:00 UTC by us31337

Добавлена настройка - Показывать только основные группы исполнителей
При этом по умолчанию не показываются
Temporary Group
Delegation Group
Escalation Group

2021-01-30 12:02 UTC, AlexMisha requested changes

2021-01-30 12:02 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/ListAllExecutorsFormTag.java
> +                if (executorsWhichNotDisplayByDefault.contains(executor.getClass())) {
У списков операция `contains` - O(n), а у `HashSet` - O(1). Предлагаю заменить

2021-01-30 12:02 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/ListAllExecutorsFormTag.java
> +    {
Читабельнее в конструкторе заполнить

2021-01-30 12:02 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/ListAllExecutorsFormTag.java
> +import ru.runa.common.web.html.*;
Съехали импорты, просьба свериться с код стайлом https://runawfe.ru/DevelopersInfo#CodeStyle;

2021-01-30 12:02 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/af/web/tag/ListAllExecutorsFormTag.java
> +    private final List<Class<? extends TemporaryGroup>> executorsWhichNotDisplayByDefault = new ArrayList<>();
`notDisplayableExecutorsByDefault` ?

2021-02-03 15:04 UTC, AlexMisha requested changes

2023-05-19 09:49 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-server/commit/6c24c11d438ea1a57825bed32a3a7800e3f0df18

2023-05-19 09:49 UTC, closed without merging