1452 Удобный/простой/лёгкий вариант смены сообщения "Экземпляр процесса №___ запущен"
processtech/runawfe-free-server pull request #213
Opened 2021-01-29 20:14 UTC by CompeCompe

Добавлен пункт в настройках для изменения шаблона сообщения при запуске нового процесса.

В классах StartProcessAction и SubmitStartProcessFormAction добавлено условие для выбора использования пользовательского шаблона сообщения или стандартного.

2021-02-04 09:47 UTC, AlexMisha requested changes
Просьба свериться с код стайлом https://runawfe.ru/DevelopersInfo#CodeStyle;
Есть некоторые нарушения вроде отсутствия пробелов после запятой

2021-02-04 09:47 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/action/SubmitStartProcessFormAction.java
> +            return new ActionMessage(RESOURCES.getStringProperty(MessagesProcesses.PROCESS_STARTED_CUSTOM.getKey()).replace("{id}",processId.toString()).replace("{name}",user.getName()),false);
Для форматирования лучше воспользоваться `MessageFormat`

2021-02-04 09:47 UTC, AlexMisha commented on wfe-web/src/main/resources/settingsList.xml
> +	<properties_file title="struts.properties">
А зачем класть в отдельный файл? Логичнее в web.properties, там как раз лежат настройки, связанные с интерфейсом

2021-02-04 09:47 UTC, AlexMisha commented on wfe-web/src/main/webapp/WEB-INF/classes/settingsDescriptions_ru.properties
> +struts.properties_process.started.custom = �������� ������ ���������, ����������������� � ������� ������ ��������. ��� ���������� Id �������� �������� � ������ {id}, ��� ���������� ����� ������������
См. как выполнен перевод для других названий, там unicode

2021-02-06 11:47 UTC, AlexMisha requested changes
Просьба почистить pr от лишних изменений

2021-02-06 11:47 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +    public static String getCustomMessageTemplate() {
custom message template для чего? Стоит конкретизировать

2021-02-06 11:47 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/action/BaseProcessFormAction.java
> - *
По файлу тогда изменения надо убрать, раз фактически их нет

2021-02-06 11:47 UTC, AlexMisha commented on wfe-web/src/main/resources/settingsList.xml
> -
Лишнее изменение

2021-02-06 11:47 UTC, AlexMisha commented on wfe-web/src/main/resources/web.properties
> +process.started=
Теоретически пользователь может захотеть, чтобы никакое сообщение не выводилось. Наверное, лучше тогда тут значение по умолчанию не указывать? В коде сравнивать с null

2021-02-06 11:47 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +
Не уверен, но вроде бы по код стайлу у нас не должно быть пробелов в импортах, просьба проверить

2021-02-09 15:31 UTC, AlexMisha requested changes
Пара небольших замечаний

2021-02-09 15:31 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/common/WebResources.java
> +    public static String getCustomTemplateForProcessStartMessage() {
```suggestion
    public static String getProcessStartedMessage() {
```
т.к. мя свойства - `process.started`

2021-02-09 15:31 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/action/SubmitStartProcessFormAction.java
> +
Пробел лишний

2021-02-10 09:49 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:50 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-server/commit/e28c916537f88f89cdff2bed8ffcc689e030c932

2023-05-19 09:50 UTC, closed without merging