Задача 1880
processtech/runawfe-free-server pull request #215
Opened 2021-02-01 19:41 UTC by hagaka

На странице Система в разделе "Загрузить файл с данными" в строке "Действия с паролем для источников данных" надписи изменяли радиобатоны в строке "Действия с паролем" вместо радиобатонов своей строки. Этот баг исправлен.

2021-02-03 11:44 UTC, AlexMisha requested changes
Одно небольшое замечание

2021-02-03 11:44 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/action/ImportDataFileAction.java
> +    public static final String SET_PASSWORD_DATA_SOURCE = "setPasswordDataSource";
По-английски, наверное, будет лучше `SET_DATA_SOURCE_PASSWORD`. И свойство ниже аналогично

2021-02-03 14:43 UTC, hagaka commented on wfe-web/src/main/java/ru/runa/wf/web/tag/ImportDataFileTag.java
>          label.addElement(new StringElement(MessagesOther.LABEL_DATAFILE_SET_PASSWORD_DATA_SOURCE.message(pageContext)));
Называл по аналогии с `LABEL_DATAFILE_SET_PASSWORD_DATA_SOURCE` здесь. Все равно изменять?

2021-02-04 17:37 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/tag/ImportDataFileTag.java
>          label.addElement(new StringElement(MessagesOther.LABEL_DATAFILE_SET_PASSWORD_DATA_SOURCE.message(pageContext)));
Ок, если по аналогии, то можно оставить так

2021-02-04 17:37 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:51 UTC, dofs197 commented
https://gitlab.processtech.ru/shared/runawfe-professional-server/-/commit/e1a05d23f70ac9ef0b7f327f3caf325545cbec22

2023-05-19 09:51 UTC, closed without merging