Issue2083
processtech/runawfe-free-server pull request #222
Opened 2021-02-19 08:44 UTC by OlegGirevoy

2021-02-19 09:58 UTC, AlexMisha requested changes

2021-02-19 09:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/SessionInfo.java
> +@Setter
`SessionInfo` лучше сделать immutable, т.е. без сеттеров. Поля `final`

2021-02-19 09:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/SessionInfo.java
> +        return Objects.hash(getId());
Лучше пользоваться напрямую полем, а не геттером

2021-02-19 09:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        if (sessions.get(userId) == null) {
Тут уместнее воспользоваться `computeIfAbsent`.
Однако вследствие используемой версии спринга придется делать анонимный класс реализацию `Function`.
Этого можно избежать, если завести приватный статический класс-реализацию и сразу завести его инстанс в приватную переменную. Тогда можно будет переиспользовать одну и ту же функцию.

2021-02-19 09:58 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +                messageSender.handleMessage(dto, Optional.ofNullable(sessionInfo.getSession()));
Похоже, придется поменять сигнатуру message sender'ов.
В чем проблема:
В дальнейшем планируется реализовать отправку email уведомлений о новых сообщениях чата (`MailMessageSender`). Если `MailMessageSender` будет получать по вызову на каждую сессию, то отправится n уведомлений вместо одного.

Нужно сделать так, чтобы `MessageSender` принимал вторым параметром `Set<Session>`. По идее он всегда будет not null, поэтому `Optional` не нужен.
И тесты `SessionMessageSenderTest` поправить

2021-02-20 07:35 UTC, OlegGirevoy commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +                messageSender.handleMessage(dto, Optional.ofNullable(sessionInfo.getSession()));
Set<Session> или Set<SessionInfo>?

2021-02-20 07:51 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +                messageSender.handleMessage(dto, Optional.ofNullable(sessionInfo.getSession()));
Вообще `Set<Session>`, но придется мапить. Можно тогда `Set<SessionInfo>`

2021-02-22 13:15 UTC, OlegGirevoy commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        if (sessions.get(userId) == null) {
1. Из-за версии спринга нельзя воспользоваться computeIfAbsent, или нельзя воспользоваться лямбдой в параметре этого метода и поэтому нужно создавать инстанс Funktion и его передавать в параметр computeIfAbsent? В чём ограничение?
2.
> завести приватный статический класс-реализацию и сразу завести его инстанс в приватную переменную.
Не до конца понял формулировку. Если сделать так:
![image](https://user-images.githubusercontent.com/51205923/108712635-42dc7400-7541-11eb-89bf-acbe2b445deb.png)
то нет доступа к Session. Если так:
![image](https://user-images.githubusercontent.com/51205923/108709077-71a41b80-753c-11eb-8490-6c32606eccaf.png)
то можно Session передавать в конструктор, но конструктор тогда нужно вызывать только в методе addSession, потому что Session в любом случае только там доступен.

3. По поводу `computeIfAbsent` - в нём выполняется только условие, когда в мапе нету нужного userId, а нам нужно ещё и условие, когда userId есть, но к нему нужно добавить новую сессию. Для этого можно использовать computeIfPresent и эти два условия разделять if'ом, как сейчас и есть. И для computeIfPresent нужен другой функциональный интерфейс, нужно будет создавать ещё один приватный класс - будет очень громоздко.

4.
> Тогда можно будет переиспользовать одну и ту же функцию.

Для чего её переиспользовать? У нас же один раз будет вызываться `computeIfAbsent`.

2021-02-22 20:11 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        if (sessions.get(userId) == null) {
> Из-за версии спринга нельзя воспользоваться computeIfAbsent, или нельзя воспользоваться лямбдой в параметре этого метода и поэтому нужно создавать инстанс Funktion и его передавать в параметр computeIfAbsent? В чём ограничение?

Нельзя воспользоваться лямбдой (используемая спрингом версия cglib/asm не поддерживает наличие в исходном коде некоторых jvm инструкций)

2. Функция должна быть чистой, т.е. из нее просто надо вернуть новый set. См. декларацию `computeIfAbsent`, вернет сет. Либо созданный, либо старый, если по переданному ключу уже есть значение в мапе.

> По поводу computeIfAbsent - в нём выполняется только условие, когда в мапе нету нужного userId, а нам нужно ещё и условие, когда userId есть и добавить новую сессию. Для этого можно использовать computeIfPresent и эти два условия разделять if'ом, как сейчас и есть. И для computeIfPresent нужен другой функциональный интерфейс, нужно будет создавать ещё один приватный класс - будет очень громоздко

Нет, нам надо только получить сет из мапы. Далее в сет можно добавить еще одну сессию, без лишних `computeIfPresent`

> Для чего её переиспользовать? У нас же один раз будет вызываться computeIfAbsent

`computeIfAbsent` будет вызываться ровно столько раз, сколько будет первичных открытий сессий, т.к. каждый сет - это набор сессий одного и того же пользователя. А у нас хранится мапа userId -> userSessions. Соответственно на каждого пользователя будет вызван `computeIfAbsent`, т.к. изначально мапа пустая

2021-02-23 11:20 UTC, AlexMisha requested changes

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/SessionMessageSender.java
> +        if (sessions.isEmpty()) {
Сюда может прийти `null`, если у пользователя еще не открыто ни одной сессии. Надо дополнительно проверить на `null`

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/SessionMessageSender.java
> +                    ChatSessionUtils.getUser(sessions.iterator().next().getSession()).getName(), e);
Если упадет отправка для первой сессии, то остальные сессии не получат сообщение. `try/catch` нужен в цикле
При этом извлекать пользователя из сессии и логгировать изначально не совсем корректно, т.к. ошибка при отправке сообщения может означать, что сессия уже была закрыта, т.е. доступа к атрибутам сессии нет. Можно ограничиться логгированием id сессии и исключения

Также необходимо изменение логики делегирования отправки:
Если хотя бы 1 сессия пользователя получила broadcast, то делегировать исполнение в другой sender не нужно
Поведение надо покрыть тестами

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +            messageSender.handleMessage(dto, sessionsSet);
```suggestion
            messageSender.handleMessage(dto, sessions.get(id));
```
Тут нет особого смысла рязделять

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +import static org.mockito.ArgumentMatchers.*;
Импорты слетели, просьба свериться с https://runawfe.ru/DevelopersInfo#CodeStyle;

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
> +        Set<SessionInfo> sessionSet = sessions.computeIfAbsent(userId, CREATE_SET);
```suggestion
        sessions.computeIfAbsent(userId, CREATE_SET).add(new SessionInfo(session));
```

2021-02-23 11:20 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/socket/ChatSessionHandler.java
>          Long userId = user.getActor().getId();
```suggestion
        Long userId = ChatSessionUtils.getUser(session).getActor().getId();
```

2021-02-23 14:59 UTC, AlexMisha requested changes

2021-02-23 14:59 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/sender/SessionMessageSender.java
> +        boolean isAnyBroadcastSending = false;
```suggestion
        boolean isAnyBroadcastSent = false;
```
По-английски, думаю, так правильнее будет

2021-02-23 14:59 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    private Session session2;
Тесты получаются запутанные, т.к. разделяют состояние полей. Сессии, remote и dto лучше мокать непосредственно в тестовых методах с нужным поведением для каждого теста

2021-02-24 07:46 UTC, OlegGirevoy commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    private Session session2;
Тут две сессии не для разных состояний, а для имитации ситуации, когда для одного пользователя открыто несколько сессий. Можно мок только этой session2 перенести в тестовый метод, эта переменная только в одном методе нужна. Не будет ли много повторяющегося кода, если всё то, что происходит в методе init будет дублироваться в каждом тестовом методе?

> Сессии, remote и dto лучше мокать непосредственно в тестовых методах с нужным поведением для каждого теста

Не будет ли много повторяющегося кода, если в каждом методе мокать эти объекты и дублировать код из метода init?

2021-02-24 16:21 UTC, AlexMisha requested changes

2021-02-24 16:21 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    private Set<SessionInfo> sessionsSet = Collections.newSetFromMap(new ConcurrentHashMap<>());
`sessionsSet` тоже отдельный для каждого теста.

`Collections.newSetFromMap` -> `newHashSet` со статик импортом. В тестах ведь многопоточность не нужна

2021-02-24 16:21 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    public void whenOneOfFewSessionsSendError_thenDontSendDelegated() throws IOException {
Тест скорее покрывает, что "если хотя бы 1 отправка успешна, то делегат не вызывался", чем "если 1 отправка с ошибкой, то делегат не вызывался".
Поэтому

```suggestion
    public void whenAnySessionSendSuccess_thenDelegateNotInvoked() throws IOException {
```

2021-02-24 16:21 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        doThrow(new IOException()).when(basic).sendText("errorTest");
Тесты запускались? `basic` используется и для 1, и для 2 сессии, т.е. по идее при отправке в обе сессии должна была упасть ошибка, т.е. должно было произойти делегирование

2021-02-24 16:21 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        verify(mailMessageSender).handleMessage(notNull(), isNull());
null'ы лучше не отправлять в другой класс. Стоит в реализации изменить передачу на `emptySet` и тогда тут `eq(emptySet())`

2021-02-24 16:25 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    private Session session2;
В тестах дублирование логики не столь принципиально, потому что если тесты однажды упадут (а это скорее всего произойдет), то тому, кто их запустит, будет проще отследить логику тестов и понять, почему они упали, если вся логика по подготовке данных/инициированию запуска тестируемых классов/проверке результатов будет непосредственно в тестовом методе

2021-02-25 04:46 UTC, OlegGirevoy commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        doThrow(new IOException()).when(basic).sendText("errorTest");
Выброс эксепшена происходит только если basic получает строку "errorTest". А в следующем when один раз отправляется "errorTest", а второй раз "testContent". 
`when(chatObjectMapper.writeValueAsString(dto)).thenReturn("errorTest").thenReturn("testContent");`
Поэтому эксепшен только один раз выбрасывается.

2021-02-25 04:58 UTC, OlegGirevoy commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        verify(mailMessageSender).handleMessage(notNull(), isNull());
В следующем за этим тест-методе так и есть, а здесь я именно на null проверяю, у тас же в SessionMessageSender.handleMessage в первом условии проверка и на null, и на пустой Set. Могу убрать этот метод, если нужно избегать передачи null.

2021-02-25 09:10 UTC, AlexMisha requested changes

2021-02-25 09:10 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +    public static final <T> Set<T> newHashSet(T... objs) {
Такой метод есть в guava `Sets.newHashSet`

2021-02-25 09:10 UTC, AlexMisha commented on wfe-core/src/test/java/ru/runa/wfe/chat/sender/SessionMessageSenderTest.java
> +        verify(mailMessageSender).handleMessage(notNull(), isNull());
Имею ввиду, если пришел `null` в `SessionMessageSender`, то лучше передавать в MailMessageSender не `null`, а `Collections.emptySet()`

2021-02-25 10:08 UTC, AlexMisha approved these changes
:+1:

2021-02-25 10:08 UTC, merged