Rm2093 Реализация пункта меню "Чаты" в стиле старого интерфейса.
processtech/runawfe-free-server pull request #226
Opened 2021-02-22 16:26 UTC by insoftjla

* Пункт "Чаты" перенесен на отдельную страницу.
 * Столбцы таблицы: Номер | Процесс | Непрочитанные сообщения

2021-02-22 20:41 UTC, AlexMisha requested changes

2021-02-22 20:41 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/security/SecuredObjectType.java
> +    public static final SecuredObjectType CHAT_ROOMS = new SecuredObjectType("CHAT_ROOMS", false);
В этом есть необходимость? Пока что не было в планах ограничивать пользователям доступ к вкладке

2021-02-22 20:41 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/tag/ListChatRoomsFormTag.java
> +        final Map<Long, Long> activeChats = Delegates.getChatService().getNewMessagesCounts(getUser());
Тут получается 2 (или больше) запроса в БД с потенциальной передачей по ejb (`ChatService` может быть remote), которых хотелось бы избежать.

Могу предложить следующую идею оптимизации:
Создаем `HashMap` -> выгружаем все `ChatMessageRecipient.message` пользователя -> цикл по полученным -> кладем в мапу ключ `new WfProcess(ChatMessage.message)`, значение - список сообщений (добавляем то, которое доступно на данной итерации) -> цикл по получившейся мапе, где ключ - `WfProcess`, значение - `List.size()`

2021-02-22 20:41 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/tag/ListChatRoomsFormTag.java
> +    class ChatUrlStrategy implements ItemUrlStrategy {
Делать вложенный не статический класс - не совсем хорошая практика (кроме явной необходимости), т.к. не статический вложенный класс содержит в себе ссылку на внешний. Порой в процессе рефакторингов про это забывают, и в итоге случаются утечки памяти.
Если и делать вложенным, то статическим. Все необходимое можно передать в конструкторе

2021-02-22 20:41 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/tag/ListChatRoomsFormTag.java
> +        final Map<Long, Long> activeChats = Delegates.getChatService().getNewMessagesCounts(getUser());
Это все имеется ввиду делать внутри `ChatLogic`, чтобы в тэг пришли готовые к использованию значения

2021-02-25 15:15 UTC, AlexMisha requested changes

2021-02-25 15:15 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/execution/ProcessChatRoomClassPresentation.java
> +    static class ChatMessageRecipientDbSource extends DefaultDbSource {
Получается, в нем нет смысла?

2021-02-25 15:15 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/html/ChatRoomTdBuilder.java
> +            element = new StringElement(getValue(object, env));
На страницу чата можно всем пользователям, для которых есть запись в `chatMessageRecipient`, т.е. тут надо всегда ссылку рисовать

2021-02-25 15:15 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/html/ChatRoomTdBuilder.java
> +public class ChatRoomTdBuilder extends BaseTdBuilder {
`ChatNewMessagesCountTdBuilder`?

2021-02-26 13:15 UTC, AlexMisha requested changes

2021-02-26 13:15 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/ChatRoomClassPresentation.java
> +                        FieldFilterMode.DATABASE, "ru.runa.wf.web.html.ChatRoomTdBuilder", new Object[]{Permission.READ, "processId"})});
Тут использование не изменилось на `ChatNewMessagesCountTdBuilder`

2021-02-26 13:15 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/chat/dao/ChatMessageDao.java
> +                .from(cr).join(cr.message.process, p).where(cr.executor.eq(actor)).groupBy(p.id, p.deployment.name).fetch();
Проверял генерируемые запросы, там нет лишних селектов на deployment, executor или message?

2021-02-26 15:34 UTC, insoftjla commented on wfe-core/src/main/java/ru/runa/wfe/chat/dao/ChatMessageDao.java
> +                .from(cr).join(cr.message.process, p).where(cr.executor.eq(actor)).groupBy(p.id, p.deployment.name).fetch();
Да, смотрел, запрос без лишних селектов.
![изображение](https://user-images.githubusercontent.com/59407764/109320629-e2a74400-7858-11eb-9946-02516bb79363.png)

2021-02-26 18:34 UTC, AlexMisha approved these changes

2021-02-26 18:34 UTC, merged