#2003 Одиночный выбор из списка пользовательских переменных.
processtech/runawfe-free-server pull request #230
Opened 2021-03-01 22:47 UTC by insoftjla

* логика перенесена в `AbstractSelectFromUserTypeList`;
 * классы `SingleSelectFromUserTypeList` и `MultipleSelectFromUserTypeList` расширяют `AbstractSelectFromUserTypeList` и реализует метод `isMultiple()`;
 * для работы необходимо добавить компонент, в `plugin.xml (runawfe-free-devstudio-master)`, на подобии `MultipleSelectFromUserTypeList`, заменив первый параметр на 
 ```xml
        <param
            name="%Param.Variable"
            optional="false"
            type="varfinder"
            variableAccess="WRITE"
            variableTypeFilter="java.lang.Object">
        </param>
```

2021-03-03 11:53 UTC, AlexMisha requested changes

2021-03-03 11:53 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/ftl/component/AbstractSelectFromUserTypeList.java
> +    private static final long serialVersionUID = 1L;
Лучше автоматически сгенерировать в идее (alt + enter)

2021-03-03 11:53 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/ftl/component/AbstractSelectFromUserTypeList.java
> +        result.put(getVariableNameForSubmissionProcessing(), selected);
`getVariableNameForSubmissionProcessing()` уже вызывался выше, лучше сохранить и переиспользовать

2021-03-03 11:53 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/ftl/component/AbstractSelectFromUserTypeList.java
> +            List<UserTypeMap> selectedList = (List<UserTypeMap>) getInputVariable().getValue();
`inputVariable` - это разве не та переменная, в которую будет записан результат? Т.е. для single select - это будет `UserTypeMap`. Тогда возможен `ClassCastException`

2021-03-04 09:49 UTC, AlexMisha requested changes

2021-03-04 09:49 UTC, AlexMisha commented on wfe-web/src/main/java/ru/runa/wf/web/ftl/component/MultipleSelectFromUserTypeList.java
>      private static final long serialVersionUID = 1L;
Для наследников аналогично

2021-03-09 11:24 UTC, AlexMisha approved these changes
:+1:

2023-05-19 09:51 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-server/commit/bb253f38e596f851c07b72c2865cb77458c3921e

2023-05-19 09:51 UTC, closed without merging