Добавлен обработчик для "Бизнес правила", внесены необходимые изменения
processtech/runawfe-free-server pull request #234
Opened 2021-04-01 04:26 UTC by zin1995

Добавлен обработчик для "Бизнес правила", внесены необходимые изменения для правильной работы обработчика

2021-04-06 12:23 UTC, AlexMisha requested changes

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +    private static final long serialVersionUID = 1L;
Его лучше сделать более уникальным

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +//            log.debug("gateway " + name + " is treated as decision gateway");
Лишние комменты стоит удалить

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +            log.debug("gateway " + name + " is treated as merge gateway");
Не увидел в постановке требований к такому поведению. Обсуждалось лично?

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/resources/localizations.ru.xml
> +  <artifact enabled="true" name="ru.runa.wfe.extension.handler.var.BusinessRuleHandler" label="Бизнес правило"/>
```suggestion
  <artifact enabled="true" name="ru.runa.wfe.extension.handler.var.BusinessRuleHandler" label="Бизнес-правило"/>
```
?

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +    public void setDelegation(Delegation delegation) {
lombok `@Setter`

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/extension/handler/var/BusinessRuleHandler.java
> +		GroovyDecisionHandler groovyDecisionHandler = new GroovyDecisionHandler();
Тут явно что-то с отступами. Просьба сверить весь pr с https://runawfe.ru/DevelopersInfo#CodeStyle;

2021-04-06 12:23 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/extension/handler/var/BusinessRuleHandler.java
> +		String function = groovyDecisionHandler.decide(executionContext);
Из постановки:

> Сверху-вниз последовательно перебираются все строки таблицы. Для каждой строки проверяется условие. Если оно истинно (т.е. равно true), то выполняется формула.

Если я правильно понял, должны выполниться все формулы, для которых условие вернуло `true`. Или я не прав?
Если прав, то, судя по коду, выполнится максимум 1 формула

2021-04-27 08:29 UTC, AlexMisha requested changes

2021-04-27 08:29 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +            throw new NullPointerException();
Скорее надо бросать `IllegalStateException`, т.к. тут невалидное состояние объекта
И исключения желательно бросать в начале метода, т.е.:
```
if (delegation == null) {
  throw new IllegalStateException(описание);
}
... дальше тело метода
```

2021-04-27 08:29 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +        if (delegation != null) {
А если `delegation` в итоге `null` - это валидно? По-моему нет

2021-04-27 08:29 UTC, AlexMisha commented on wfe-core/src/main/java/ru/runa/wfe/lang/bpmn2/BusinessRule.java
> +    public void setDelegation(Delegation delegation) {
Не исправлено

2021-04-27 08:29 UTC, AlexMisha commented on wfe-core/src/main/resources/localizations.ru.xml
> +  <artifact enabled="false" name="ru.runa.wfe.extension.handler.var.BusinessRuleHandler" label="Бизнес-правило"/>
А тут точно тогда нужна локализация, раз она disabled?

2021-05-11 08:10 UTC, AlexMisha approved these changes
:+1:

2021-07-15 11:52 UTC, CrimsonParade commented on wfe-core/src/main/java/ru/runa/wfe/graph/image/figure/bpmn/BpmnFigureFactory.java
> +             figure = new RoundedRect("image/bpmn/businessRule.png");
Похоже, лишний пробел

2023-05-19 09:52 UTC, dofs197 commented
https://github.com/processtech/runawfe-free-server/commit/f4d875510081abac1c723d2bb07d0ee6a5690563

2023-05-19 09:52 UTC, closed without merging